%Muhammad Awias
%awais12506@gmail.com
function [] = plot_func()
% Help
S.fh = figure('units','pixels',...
              'position',[300 300 300 300],...
              'menubar','none',...
              'name','plot_func',...
              'numbertitle','off',...
              'resize','off');      
          
S.ed = uicontrol('style','edit',...
                 'unit','pix',...
                 'position',[70 255 180 40],...
                 'string','Enter func of x,a,b,c',...
                 'fontsize',10);
             
S.eda = uicontrol('style','edit',...
                 'unit','pix',...
                 'position',[150 200 100 40],...
                 'string','',...
                 'fontsize',10);    
S.edb = uicontrol('style','edit',...
                 'unit','pix',...
                 'position',[150 150 100 40],...
                 'string','',...
                 'fontsize',10);
S.edc = uicontrol('style','edit',...
                 'unit','pix',...
                 'position',[150 100 100 40],...
                 'string','',...
                 'fontsize',10);  
S.sta = uicontrol('style','text',...
                 'unit','pix',...
                 'position',[10 205 100 30],...
                 'string','Enter a',...
                 'fontsize',10); 
S.stb = uicontrol('style','text',...
                 'unit','pix',...
                 'position',[10 155 100 30],...
                 'string','Enter b',...
                 'fontsize',10); 
S.sta = uicontrol('style','text',...
                 'unit','pix',...
                 'position',[10 105 100 30],...
                 'string','Enter c',...
                 'fontsize',10);             
S.pb = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[55 20 180 35],...
                 'string','plot it!',...
                 'fontsize',14);
set(S.pb,'callback',{@pb_call,S})  % Set callback.
uicontrol(S.ed)
function [] = pb_call(varargin)
% Callback for pushbutton.
S = varargin{3};  % Get the structure.
func = vectorize(inline(get(S.ed,'string'),'a','b','c','x'));
%Getting all the values of a,b and c
a=get(S.eda,'string');
a=str2num(a);
b=get(S.edb,'string');
b=str2num(b);
c=get(S.edc,'string');
c=str2num(c);
x = -1000:.1:1000;
figure
plot(x,func(a,b,c,x))